### ISSUE TITLE
Unrecgonized Option: -J-XX, -J-Xmx8G

### ISSUE THREAD

**Issue by xuzhaoqing** [richemslie/ggplib#1]
When I followed the instructions to install ggplib, I'm stuck when running perftest.sh for testing. It seems '-J-XX' in /src/ggplib/propnet/getpropnet.py should be '-XX', and ' -J-Xmx8G' should be '-Xmx8G', at least when I modified it, things worked fine for me. Thanks!

**Comment by richemslie** [comment]
Thanks.  I am not sure if those options were specific to some Java version.  I tried without extraneous -J s on my install, and it works fine - so will push that change.
Incidentally, if those options fail, it is suppose to retry without any extra Java options.  Did that not work for you?

**Comment by xuzhaoqing** [comment]
Thanks for your help, and I didn't try compiling it without any extra Java options, but removing -J is just enough.
