### ISSUE TITLE
Where is ggtest1.sh?

### ISSUE THREAD

**Issue by zhaoqxu** [richemslie/ggplib#2]
Hi, I couldn't find ggtest1.sh file that is mentioned in your doc/README.rst. Could you please upload it? Thanks!

**Comment by richemslie** [comment]
Hi, thanks for the report!
The instructions are a little out of date, sorry.  I'll update them over the next few days.
There is a general play.py command that can run at the top level of ggplib.

$ cd src/ggplib
$ python play.py ggtest1 2905
or
$ python play.py random 2905

**Comment by xuzhaoqing** [comment]
Thanks, it works
